version: '3'
services:
  website:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: senither/hypixel-skyblock-guild-scanner
    ports:
      - 8080:80
    depends_on:
      - facade
  facade:
    restart: unless-stopped
    image: senither/hypixel-skyblock-facade
    ports:
      - 9281:9281
