version: '3'
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: senither/hypixel-skyblock-guild-scanner
    ports:
      - '${APP_PORT:-8080}:80'
    depends_on:
      - api
  api:
    restart: unless-stopped
    image: senither/hypixel-skyblock-facade
    ports:
      - '${API_PORT:-9281}:9281'
